### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found class kilim.test.TestAbstractExtends$StandardService, but interface was expected

### ISSUE THREAD

**Issue by yyonghe** [nqzero/kilim#10]
A is a interface that has a method a(), B is a abstract class that implements A and has a abstract method b(), C is a instance class that extends from B. The method a() called method b() in B class. When we create a C install and call c.b() in application. There will be a IncompatibleClassChangeError, like this:
java.lang.IncompatibleClassChangeError: Found class kilim.test.TestAbstractExtends$StandardService, but interface was expected
	at kilim.test.TestAbstractExtends$StandardService.$shim$1(TestAbstractExtends.java)
	at kilim.test.TestAbstractExtends$StandardService.service(TestAbstractExtends.java:27)
	at kilim.test.TestAbstractExtends$1.$shim$1(TestAbstractExtends.java)
	at kilim.test.TestAbstractExtends$1.execute(TestAbstractExtends.java:46)
	at kilim.Task.run(Task.java:538)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Classes define like:

	public static interface Service {
		public void service(String message) throws Pausable;
	}
	
	public static abstract class StandardService implements Service {

		@Override
		public void service(String message) throws Pausable {
			doService(message);
		}
		
		public abstract void doService(String message) throws Pausable;

	}
	
	public static class MyService extends StandardService {

		@Override
		public void doService(String message) throws Pausable {
			System.out.println(message);
		}
	}

**Comment by nqzero** [comment]
thanks for the bug report. i'll take a look at the code and your pull request

**Comment by nqzero** [comment]
thanks for the excellent bug report and fix @hyleeon 

also, thanks for fixing the permissions (most files in the main source tree had execute permission). i've integrated both changes

**Comment by nqzero** [comment]
i haven't deployed an artifact to maven central with this fix yet (planning on doing the next pre-release this weekend or monday). if this is a priority for you, let me know and i'll deploy it tmrw

**Comment by yyonghe** [comment]
No problem, we are upgrading our jdk to Java 8 and kilim to kilim 2.0, Now in testing phase and we are using my fixed branch to test, until your artifact deployed we will switch to it.

**Comment by nqzero** [comment]
ok - i'll a quick (otherwise unannounced) release tonight for java 8, 9 and 11

**Comment by yyonghe** [comment]
thank you very much.

**Comment by nqzero** [comment]
i just released 2.0.0-26

it usually takes about 20 minutes to show up in maven central

the kilim tests are green, but i haven't tried anything beyond that (usually i test some external projects that depend on kilim before making a release). if you run into problems i'll probably be awake for another hour

**Comment by nqzero** [comment]
2.0.0-26 is live, and i used it for a very simple demo and it worked

**Comment by yyonghe** [comment]
ok. we'll use this version to test.
