### ISSUE TITLE
Issue with nested exception handling

### ISSUE THREAD

**Issue by aleksandarmilisic** [nqzero/kilim#13]
Consider the following:

````
try {
    obj.execute();
    System.out.print(“A”)
} catch (Exception e) {
    try {
        obj.executeFallback();
        System.out.print (“C”)
    } catch (Exception e) {
        System.out.print (“D”)
    } finally {
        System.out.print (“E”)
    }              
} finally {
    System.out.print (“B”)
}
```

In the weaved code, the behaviour is as follows:

- If obj.execute() does not throws an exception, output is as expected: **AB**
- If obj.execute() throws an exception but obj.executeFallback() doesn’t , expected output is **CEB**, but actual output is **CB** .
- If both obj.execute() and obj.executeFallabck() throw exceptions , expected output is **DEB**, but actual output is **B** .

However,
**if I move the content of the top-level catch block to a private method and call it, output is as expected.**


Note: We are currently required to use ASM version 5.2

**Comment by nqzero** [comment]
could you make a github project with that example, ie a pom and a single source file ? does the ASM version change the behavior ?

**Comment by aleksandarmilisic** [comment]
Hi,

sure, the team member that reported it is away for a few days so hopefully
we can put this together when he's back some time next week.

Thanks!

**Comment by nqzero** [comment]
@aleksandarmilisic any progress on getting a working demo of this issue ?

**Comment by aleksandarmilisic** [comment]
[kilim-bug.zip](https://github.com/nqzero/kilim/files/3051054/kilim-bug.zip)

Apologies for the very late reply, had other things come up unexpectedly.

I've attached a zip file with a maven project and some instructions that illustrate the issue.
Not sure if you want to re-open this issue or create a new one, I will leave that to you.

Thanks for your help!

**Comment by nqzero** [comment]
this code is far too complex to demonstrate the problem - i'd need to understand your classloaders and weaver before even getting to kilim. i'll try to figure out the core issue that you're trying to demonstrate and reproduce it using the core kilim tools, but i'm not going to try to debug your kilim-bug.zip

bug examples should be a single java file with a main plus a pom.xml, and should use the fewest lines of code possible

if you need help debugging a more complex app or isolating a problem, commercial support is available (i'm available for contract work and i believe sriram is too, or at least, has been at times)

i appreciate the work that you put into developing this, but it isn't a model that we can support directly

**Comment by nqzero** [comment]
i ended up deciding to just try running your test on a VPS. with 2.0.0-15 it fails, with 2.0.2 (ie 69c060d, the commit that closed this bug report on march 27) it passes

there's a small change needed for KilimWeaver calling the mirror constructor

```
-		KilimContext context = new KilimContext(new CachedClassMirrors(new KilimClassLoader(), classLoader));
+		KilimContext context = new KilimContext(new CachedClassMirrors(classLoader));
```

2.0.2 isn't in maven central yet, so you'll need to install kilim locally
