### ISSUE TITLE
asm 6.0 support

### ISSUE THREAD

**Issue by pellcorp** [nqzero/kilim#5]
Will kilim 2.0.0 support asm 6.0?

**Comment by nqzero** [comment]
i haven't scoped this out enough to know 100% that it's feasible. that said, i'll be shocked if it's not feasible and i have every intention of implementing this

i'm currently buried in non-technical work that at the latest will be done august 15 (and with luck much sooner). after that, updating kilim is my top priority

estimated completion: sept 1

**Comment by nqzero** [comment]
finished the non-technical work before the deadline so looking at this now

asm6 was integrated in 49de1f6 (HEAD~9 currently) though i'm still using asm5 opcodes. HEAD has at least nominal support for java 9, though i'm not familiar enough with java 9 to know which features will stress kilim

this is not currently deployed to maven central. i'll look at what's needed to do a release (likely nothing, but i've been away from kilim for a minute). in the meantime, can you build from source and install to maven locally ?

**Comment by pellcorp** [comment]
I am currently working through some issues even using 2.0.0-3+ (see other issue), so until I can get past that, I won't have a chance to look at asm 6.  However as soon as I have this resolved, I will be looking at asm 6 support.

**Comment by nqzero** [comment]
i'm going to hold off on deploying 2.0.0-16 to maven central till we resolve the liveness / state class problem in issue #6 since it sounds like you're already building from source. if anyone wants a new release right now, just comment

**Comment by pellcorp** [comment]
I am almost ready with a test case a few more hours at most today

**Comment by pellcorp** [comment]
Issue #6 has been closed

**Comment by pellcorp** [comment]
We successfully updated to 2.0.0-15 and our initial performance tests have been very encouraging. I plan on testing 2.0.0-16 in the next few days.

**Comment by nqzero** [comment]
my initial deployment was grossly untested (i conflated building with an older version with testing with the older version). java 9 support appears to be ok for AOT weaving (though my testing is still not quite apples to apples), but the weaving class loader fails with `IllegalAccessError`. i'm guessing that this can be worked around using `--permit-illegal-access`, but i haven't tested that yet

java 10 support is in much worse shape - at least some woven lambdas won't load. and java 10 will have the same access issues (and more complicated flags)

sorry for the overly optimistic initial claims. i've been working on the java 10 weaving issue full time and hope to have a fix by the end of the month. i may have to wait till august 15 to begin working on the access issue

**Comment by nqzero** [comment]
i just pushed ad76fb8 and released to maven central as 2.0.0-17. this resolves all known issues with java 9 and java 10 and no special runtime flags are required

to run on java 10, all pausable lambdas (even ones compiled and woven on java 8 or 9) need to be written with the last parameter being `Fiber`, eg `dummy -> { Thread.sleep(1000); }

the older (fiber-free) syntax is still supported to allow existing code for java 8 and 9 to continue to work. with java 10, this syntax appears to trigger stricter runtime validation in java 10 and silently fails with `NoClassDefFoundError`

leaving this open for the moment till i hear how your testing goes

**Comment by nqzero** [comment]
i just pushed 2.0.0-18. it's identical to 2.0.0-17. however, there's also a `<classifier>jdk9</classifier>` jar which includes the illegal access fix but not the java 10 lambda support (the java9 tag in github)

**Comment by nqzero** [comment]
haven't heard any followup for 6 weeks, so closing this use. current version in maven central is 2.0.0-25
