### ISSUE TITLE
Add "pausable" for java file inside jar 

### ISSUE THREAD

**Issue by JasonHuangHuster** [nqzero/kilim#8]
" when a method call pausable method , then it should throws pausable itself  ".

the rule make sense , but if the caller is a class inside a jar ? then the developer has to rewrite the java file in the jar . this would be very inconvenience ...  is there any more elegant way to handle this ?  :)

**Comment by nqzero** [comment]
kilim needs to store additional info about the call stack and state and transform the bytecode to allow methods to yield. this transformation is called weaving, and we only weave Pausable methods. this adds a Fiber argument to the method. so trying to call from an unwoven method won't work

in theory you could weave the calling class, ie a method that's not marked Pausable. but in practice this creates additional problems since it's not longer tractable to determine what methods need to be woven. kilim keeps things simple by refusing to go down this road

without a code snippet i'm not 100% sure what you're trying to do, but generally you've got two options

- many classes have async methods, eg jetty, spring boot, okhttp. for these classes, you can bridge between async and pausable easily. take a look at the jetty support in kilim demos

- fork a new pausable task:
```
    void myMethod() throws Pausable {}
    void blockingMethod() {
        Task.fork(() -> myMethod()).joinb();
    }

```

if you create a repo with a demo maven project with what you're trying to accomplish, i'll take a look

**Comment by JasonHuangHuster** [comment]
thanks for your reply 👍 
here's a demo .
https://github.com/JasonHuangHuster/kilim_demos/blob/master/src/main/java/demo/GuavaCacheTest.java

`
    void myMethod() throws Pausable {}
    void blockingMethod() {
        Task.fork(() -> myMethod()).joinb();
    }
`
this will work , but it will block the thread , and will cause lots of problem in a kilim based service .

**Comment by nqzero** [comment]
thanks for the code - i'll clone your repo and take a look

**Comment by nqzero** [comment]
i'm not 100% sure what you're trying to use the guava cache for, but i made my best guess and posted a pull request

https://github.com/JasonHuangHuster/kilim_demos/pull/1

the guava cache unfortunately doesn't have an async getter api and the async supplier api is only for reload, not load. to work around this, i wrapped the `get()` with a loop, and for the `load` i just return a dummy value

for the sake of being able to watch the output, i changed the refresh time to 1 second

this example could be written in a more compact form using lambdas, but i used classes and tasks to match the style that you started with

**Comment by nqzero** [comment]
i refactored the guava integration code into a `KilimCacheLoader` class which would make it easier to use Guava from Kilim

https://github.com/nqzero/kilim_guava_cache

the demo is still based on your code @JasonHuangHuster

**Comment by JasonHuangHuster** [comment]
tons of thanks ! really appreciate it ! 

your strategy is great , it could solve the problem .  we just work around the synchronous 'load()' method . but we just lost some accuracy  before the refresh is completed because of the 'dummy' initial value . 

google guava  loading cache is really elegant , i use it in every application cache scenario . but it just don't work perfectly with kilim ... the actual value fetch inside the 'load()' method  could be asynchronous . the only obstacle is the api design of guava cache ... everything will be simple and perfect if the api is asynchronous , at least it could throw pausable . 
`
       /**
     **  the load method is called synchronously . but the computeWantedValue() method is pausable , 
     ** it could be work with kilim just fine if it's not inside the load() method . 
      **/
       @Override
        public Integer load(String key) throws Exception {
            return computeWantedValue();
        }

`

i tried to rewrite the guava cache's class file , but it was a tremendous amount of work , and the base class go direct to jdk class files like 'Map.class' . so this way is infeasible 。  

do you have other elegant idea to solve this problem , i use kilim in almost all of my service . this awkward scenario keeps annoying me for a long time ... :(

**Comment by nqzero** [comment]
> but we just lost some accuracy before the refresh is completed because of the 'dummy' initial value

no accuracy is lost. the `getCache` static method detects the initial dummy value, calls `refresh` and pauses until the correct value is ready

the only cost is the added latency on the first access of a value

**Comment by JasonHuangHuster** [comment]
i got it ! thank you ! u'r a genius !

**Comment by JasonHuangHuster** [comment]
i tried this kilim cache online , but the jvm process's thread stuck in block and occupied lots of cpu and memory occasionally  , seems like several threads  fall into a loop and after that it won't come out . 


![image](https://user-images.githubusercontent.com/5965173/44592383-f0486280-a7f2-11e8-831e-991525273851.png)

![image](https://user-images.githubusercontent.com/5965173/44592392-f63e4380-a7f2-11e8-9a2f-0fb89e715ca3.png)

![image](https://user-images.githubusercontent.com/5965173/44592404-0c4c0400-a7f3-11e8-9499-f3b504651414.png)

here is the gc log , keeps saying 'Allocation Failure'

**Comment by JasonHuangHuster** [comment]
there's sth wrong with the getCache() method , if the `value` takes too long to calc , the while loop will keep refresh() , and there's lock prevent the reloading request send to the backen svr simultaneously . it's a reentrance lock ,  it's a kilim task who do the lock , and the thread which is running the task get blocked if other task which belong to another thread is reloading(means that thread holded the lock) , and the second thread will get blocked .

it's becase my io scheduler is the same with the refresh schedule , so when the calc request gets back , there's no room for it to be handled by the scheduler , becase all thread in it get blocked . it cause a dead lock . the whole process gets really slow . 

but it's wierd that , the `top` command shows the thread's cpu and mem usage is very high , it's already blocked , why it still ocupying the cpu ? the gc thread should get busy in theory ...

**Comment by nqzero** [comment]
i'll take a look

is the code that's causing this what's currently head in your kilim_demo repo ? ie, 2634d4887814976cc07f30d45c964a09f4aed025

**Comment by JasonHuangHuster** [comment]
it's a bit project and it has lots of dependent so it can't just run anywhere . 
the only difference is that i did not use the Task.fork function . cause it's a old project that use kilim 1.0 .

`package com.tencent.jungle.util;

/**
 * Created by adamshuang on 2018/8/22.
 */

import com.google.common.cache.CacheLoader;
import com.google.common.cache.LoadingCache;
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.SettableFuture;

import java.util.concurrent.ExecutionException;

import kilim.Pausable;
import kilim.Task;

public class KilimCacheLoader<KK, VV> extends CacheLoader<KK, VV> {

    public interface PausableFuture<KK> {
        void calcFutureValue(KK key, SettableFuture future) throws Pausable;
    }

    private static final Object dummy = new Object();
    PausableFuture pausableFuture;

    public KilimCacheLoader() {
    }

    public KilimCacheLoader(PausableFuture calcFutureValue) {
        this.pausableFuture = calcFutureValue;
    }

    @Override
    public VV load(KK key) {
        return (VV) dummy;
    }

    @Override
    public ListenableFuture reload(final KK key, VV oldValue) {
        final SettableFuture future = SettableFuture.create();
        new Task() {

            @Override
            public void execute() throws Pausable, Exception {
                if (pausableFuture == null) {
                    calcFutureValue(key, future);
                } else {
                    pausableFuture.calcFutureValue(key, future);
                }
            }
        }.start();

        return future;
    }

    public void calcFutureValue(KK key, SettableFuture future) throws Pausable {
    }


    public static class Getter<KK, VV> {
        LoadingCache<KK, VV> cache;
        int delay;

        public Getter(LoadingCache<KK, VV> cache, int delay) {
            this.cache = cache;
            this.delay = delay;
        }

        public VV get(KK key) throws Pausable {
            return getCache(cache, key, delay);
        }
    }


    /**
     * get a value from the cache asynchronously.
     * this method (or similar logic) must be used for all access.
     * if the key is not available immediately this method pauses until it is ready
     *
     * @param <KK>  the key type
     * @param <VV>  the value type
     * @param cache the cache to access
     * @param key   the key to search for
     * @param delay the number of milliseconds to suspend if the value is not yet available
     * @return
     * @throws Pausable
     */
    public static <KK, VV> VV getCache(LoadingCache<KK, VV> cache, KK key, int delay) throws Pausable {
        VV result = null;
        while (true) {
            try {
                result = cache.get(key);
                if (result == dummy) {

                    cache.refresh(key);
                } else {
                    return result;
                }
            } catch (ExecutionException ex) {
            }
            Task.sleep(delay);
        }
    }

    public static void main(String[] args) {

        long index = Long.MAX_VALUE;


        for (int i = 0; i < index; i++) {

            if (i < 0) {
                System.out.println("hey:" + i);
            }
        }

    }
}
`

**Comment by nqzero** [comment]
ok - i reread your discussion of the locking and i think you're correct. my simple demo is single threaded so this doesn't occur. we'll need to come up with a standalone concurrent test so we can see the problem more clearly

i'll work on it

**Comment by JasonHuangHuster** [comment]
tons of thanks for your help ... 


i add a new method in the KilimCacheLoader . i choose to give up the accuracy of  the first hit ( in my situation , few of them , cause my backend rpc will return between the delay normally ) to ensure the whole service won't get mess .  sorry for the code style ,i tried ,but it just dont display in the write way ... 

```
public static <KK, VV> VV getCacheOneShot(LoadingCache<KK, VV> cache, KK key, int delay, VV 
      dummyValue) throws Pausable {
          VV result = null;
          try {
             result = cache.get(key);
               if (result == dummyValue) {
                 cache.refresh(key);
                 Task.sleep(delay);
                return cache.get(key);
             } else {
                 return result;
             }
         } catch (ExecutionException ex) {
         }
         return dummyValue;
    }

```

**Comment by JasonHuangHuster** [comment]
here is the whole thread dump file , hope it will do some help .
[https://files.fm/u/wrwct8m7](url)

**Comment by nqzero** [comment]
i fixed one issue - multiple refreshes were happening per getCache. i also turned the demo into a stress test. it does fail occasionally, likely for the reasons you describe. i'll keep working on it

to style code, look at https://guides.github.com/features/mastering-markdown/

**Comment by nqzero** [comment]
i've gotten the race condition to occur with only 2 threads. prolly won't track down the problem tonight, but i'll try to get it tmrw. in the meantime, try out my fix for the obvious problem

eb91beb12236f0fec432818eb7571c2e2998657a

the remaining issue is with eviction and is much more rare

**Comment by JasonHuangHuster** [comment]
i'll start a issue in guava cache . maybe we could get some suggestions . guava is designed under thread mode , there may be other pitfalls . 😢

**Comment by nqzero** [comment]
i wouldn't open an issue there. this is almost certainly something i'm doing wrong - i don't 100% understand the locking / eviction scheme that guava is using

**Comment by nqzero** [comment]
had to give up on the load/reload/refresh stuff. based on the javadocs get appeared non-blocking, but during a refresh it blocks. so can't use that

i switched to get/put with kilim mailboxes doing the heavy lifting. the stress test demo runs without hanging

currently using a Cache. i'm not sure if LoadingCache would work too - the refresh cycle creates a bunch of locking and blocking that's hard to track down

i'll give it a quick look tmrw, but if it doesn't work easily i'm not sure how much longer i'll spend on it

check out the head of my repo

**Comment by JasonHuangHuster** [comment]
the refresh reload method is invoked asynchronously inside a separated ThreadPool Executor .

```
// Some keys don't need refreshing, and we want refreshes to be done asynchronously.
LoadingCache<Key, Graph> graphs = CacheBuilder.newBuilder()
       .maximumSize(1000)
       .refreshAfterWrite(1, TimeUnit.MINUTES)
       .build(
           new CacheLoader<Key, Graph>() {
             public Graph load(Key key) { // no checked exception
               return getGraphFromDatabase(key);
             }

             public ListenableFuture<Graph> reload(final Key key, Graph prevGraph) {
               if (neverNeedsRefresh(key)) {
                 return Futures.immediateFuture(prevGraph);
               } else {
                 **// asynchronous!**
                 ListenableFutureTask<Graph> task = ListenableFutureTask.create(new Callable<Graph>() {
                   public Graph call() {
                     return getGraphFromDatabase(key);
                   }
                 });
                 **executor.execute(task);**
                 return task;
               }
             }
           });
```

the new strategy you used is more like the `callable` population mode . i've committed a impl of that 
248bff8b013a3cb7f045e17ae513edc3bc8cb9ca .
the CacheLoader is more preferred is because the refresh method keeps return the old value after the value has expired , this mode is better than the callable which block the request until the new value is returned .  most keys have the same expire time , so it will cause many request get blocked under a busy  service which bring down the performance .

**Comment by nqzero** [comment]
i updated the demo to use the LoadingCache with a refresh - `get(key,callable)` uses the `callable` for the refresh so everything just works

it doesn't support your `neverNeedsRefresh` use case. i think you can handle that using `getIfPresent`. you'll need to modify `getCache` directly

a0b863ca39455767a3ca7c68cc45f946255193b3

**Comment by nqzero** [comment]
think i've got your use case working with a reasonably clean implementation. i haven't tested it with eviction yet, but i've run the demo for millions of iterations and things look normal

harder than it should have been to get the previous value because the cache doesn't have methods without side effects, eg in `getIfPresent()` if a key isn't present it invokes the loader and modifies the cache. but the logic that i needed for that was already used in `getCache` so i split it out and use it in both cases

it's the current head of my repo:

https://github.com/nqzero/kilim_guava_cache/commit/f8888fe78767952bfae8b404e67f4eabbb6a14d3

this is all pausable and without any spin locks

**Comment by JasonHuangHuster** [comment]
it looks really complicated my bro . 😂   guava is designed in thread mode , the reentrance lock used in it just does not fit in kilim .  the implementation by now is enough for my project's usage .  

I don't know what to say , really appreciated !

**Comment by nqzero** [comment]
this issue is resolved by https://github.com/nqzero/kilim_guava_cache

this is a scalable, fully async integration of Kilim with the Guava LoadingCache
