### ISSUE TITLE
can kilim  support redis 

### ISSUE THREAD

**Issue by JasonHuangHuster** [nqzero/kilim#9]
redis api is used in synchronous way usually , but i found this will cause unacceptable latency in kilim mode service . can kilim support redis ?

**Comment by nqzero** [comment]
i haven't personally used redis, nor am i familiar with the java ecosystem to support it. but i took a quick look and found this:

https://github.com/lettuce-io/lettuce-core

lettuce is a popular java client for redis with an async api so kilim should work great

looks like you should be able to do `RedisFuture.thenRun(listener)`. in your listener, call `kilim.Mailbox.putb()` and have a kilim task that calls `mb.get()` on the same mailbox. if you have trouble, make a github repo with a pom.xml for kilim and lettuce and i'll fix it up for you

also, these sorts of questions are probably better answered on the mailing list so you should subscribe to that. https://groups.google.com/forum/#!forum/kilimthreads

**Comment by nqzero** [comment]
also, if you're looking for a database that integrates nicely with kilim, you should check out my other project:

https://github.com/db4j/db4j

it's a transactional database with pure java queries. embedded only for now but once i see how other people are using it i'll release a network driver

**Comment by JasonHuangHuster** [comment]
thanks a lot !   i'll try lettuce-core  : )
